// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// TestStatExpectation
float TestStatExpectation(NumericVector sample, NumericVector Regions);
RcppExport SEXP _CramTest_TestStatExpectation(SEXP sampleSEXP, SEXP RegionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Regions(RegionsSEXP);
    rcpp_result_gen = Rcpp::wrap(TestStatExpectation(sample, Regions));
    return rcpp_result_gen;
END_RCPP
}
// TestStatMoment3
double TestStatMoment3(double n1, double n2, NumericVector sample, NumericVector Regions);
RcppExport SEXP _CramTest_TestStatMoment3(SEXP n1SEXP, SEXP n2SEXP, SEXP sampleSEXP, SEXP RegionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Regions(RegionsSEXP);
    rcpp_result_gen = Rcpp::wrap(TestStatMoment3(n1, n2, sample, Regions));
    return rcpp_result_gen;
END_RCPP
}
// TestStatVariance
double TestStatVariance(int n1, int n2, NumericVector sample, NumericVector Regions);
RcppExport SEXP _CramTest_TestStatVariance(SEXP n1SEXP, SEXP n2SEXP, SEXP sampleSEXP, SEXP RegionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Regions(RegionsSEXP);
    rcpp_result_gen = Rcpp::wrap(TestStatVariance(n1, n2, sample, Regions));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CramTest_TestStatExpectation", (DL_FUNC) &_CramTest_TestStatExpectation, 2},
    {"_CramTest_TestStatMoment3", (DL_FUNC) &_CramTest_TestStatMoment3, 4},
    {"_CramTest_TestStatVariance", (DL_FUNC) &_CramTest_TestStatVariance, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CramTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
