# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TestStatExpectation <- function(sample, Regions) {
    .Call(`_CramTest_TestStatExpectation`, sample, Regions)
}

TestStatMoment3 <- function(n1, n2, sample, Regions) {
    .Call(`_CramTest_TestStatMoment3`, n1, n2, sample, Regions)
}

TestStatVariance <- function(n1, n2, sample, Regions) {
    .Call(`_CramTest_TestStatVariance`, n1, n2, sample, Regions)
}

